services:

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: user-service/Dockerfile
    restart: no
    ports:
      - "8084:8084"
    environment:
      HOST_DB: user-db
      PORT_DB: 5432
      NAME_DB: ${USER_DB_NAME}
      USER_DB: ${USER_DB}
      PASSWORD_DB: ${PASSWORD_DB}
      TOKEN_SIGNING_KEY: ${TOKEN_SIGNING_KEY}
    depends_on:
      user-db:
        condition: service_healthy

  file-storage-service:
    container_name: file-storage-service
    build:
      context: .
      dockerfile: file-storage-service/Dockerfile
    restart: no
    ports:
      - "8082:8082"
    environment:
      HOST_DB: file-db
      PORT_DB: 5432
      NAME_DB: ${FILE_DB_NAME}
      USER_DB: ${USER_DB}
      PASSWORD_DB: ${PASSWORD_DB}
      TOKEN_SIGNING_KEY: ${TOKEN_SIGNING_KEY}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      MINIO_URL: ${MINIO_URL}
      MINIO_PORT: ${MINIO_PORT}
      USER_SERVICE_URL: http://user-service:8084
    depends_on:
      file-db:
        condition: service_healthy
      minio:
        condition: service_healthy

  user-db:
    image: postgres:16-alpine
    container_name: user-db
    restart: always
    ports:
      - "8889:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: ${USER_DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER_DB} -d ${USER_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  file-db:
    image: postgres:16-alpine
    container_name: file-db
    restart: always
    ports:
      - "8890:5432"
    volumes:
      - file_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: ${FILE_DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER_DB} -d ${FILE_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      MINIO_URL: ${MINIO_URL}
      MINIO_PORT: ${MINIO_PORT}
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  app_network:
    driver: bridge

volumes:
  user_data:
  file_data:
  minio-storage: